### PR TITLE
Update Adina-related content

### LINKED ISSUE #7: Update Adina's member profile
- [ ] Finally get a photo!
- [ ] Update the description, now that's she's done with her Masters! (@AdinaWagner)

### PR DESCRIPTION
**Pull request by AdinaWagner**
If @aqw approves my picture (its really outdated, but I don't mind being less wrinkly), this should close #7. Also addresses parts of #6 with regard to adina.wagner@st.ovgu.de --> adina.wagner@t-online.de.

Additionally, I've added my thesis to the "completed theses" in `teaching.rst`

### CODE REVIEW

**Comment by aqw** [comment]
@AdinaWagner Love the text changes. If you have a higher res version of your image, I can take another whack at it to adjust the temperature, exposure, and dimensions a bit. If not, we'll merge as is and take pictures once we're at FZJ, so it looks like you're in the same room as us. ;-)

**Comment by AdinaWagner** [comment]
I've send you the original per mail, let me know whether you think the resolution is high enough, or if want me to do sth with it to spare you work (e.g. get rid of original background) :-)

**Comment by aqw** [comment]
@AdinaWagner Thanks for the photo. With the higher res, I could abuse the exposure more with fewer visual artifacts. It looks good enough for now, in my opinion (though it's your picture, feel free to adjust as you see fit).

We'll do another photo shoot for all of us when we're at FZJ. :-)

**Comment by AdinaWagner** [comment]
Thx @aqw :-)

**Pull request merged**
