### PR TITLE
Various changes to reflect the new state of the lab

### PR DESCRIPTION
**Pull request by mih**
@aqw please have a look at the CSS flex setting -- I had no idea what I was doing.

### CODE REVIEW

**Comment by aqw** [comment]
@mih Is it ok I review on Friday? I still have some furniture I need to assemble tonight, and tomorrow is pretty well booked up.

**Comment by mih** [comment]
Absolutely. It becomes reality on Mon. That would be good enough. Thx.

**Comment by mih** [comment]
FTR: This PR seems to have updated the live page already. Dunno who set the deployment up @aqw @bpoldrack, but please have a look.

**Comment by aqw** [comment]
@mih That was a problem with the datalad website as well. It'll auto push all successful tests from branches of this repo (but not forks of the repo). I can pull the fixes from there later today. Still jumping through some paperwork hoops here at FZJ on the first day.

---Alex

**Comment by aqw** [comment]
@mih @bpoldrack, I ported the fix from datalad.org[1]. Now only master builds will autopublish.

85af5c039c1bddddf2e89fffc722e89343af6373

[1] https://github.com/datalad/datalad.org/commit/9b2cb6160cebf89ccf531b3f592f093c4f6ab787

**Pull request merged**
