### PR TITLE
add Heunis et al 2021 paper

### PR DESCRIPTION
**Pull request by jsheunis**

### CODE REVIEW

**Comment by aqw** [comment]
Thanks!

FYI: the page failed to build to build because the `preprint` link was already defined. I made them anonymous (two `_` rather than one) and it builds now.

 Merged. :-)

**Comment by jsheunis** [comment]
Thanks Alex, and sorry about that, I should have fixed it.

**Comment by aqw** [comment]
Not a problem. Just run the build locally first, and you'll catch the build errors. ;-)

**Comment by jsheunis** [comment]
Indeed, and I should push anything right before going to sleep...

**Pull request merged**
